[build]
builder = "nixpacks"
buildCommand = "echo built in 0s"

[deploy]
startCommand = "bun run scheduling/file-tasks/file-tasks.ts"
healthcheckTimeout = 1
restartPolicyType = "never"
cronSchedule = "0 * * * *"