[build]
builder = "nixpacks"
buildCommand = "echo built in 0s"

[deploy]
startCommand = "bun run scheduling/db-tasks/db-tasks.ts"
healthcheckTimeout = 1
restartPolicyType = "never"
cronSchedule = "15 * * * *"